### PR TITLE
Make python snippets able to handle arguments with type annotations.

### PR DESCRIPTION
**Pull request by galaunay**
As promised.
(Following discussion in elpy [#1343](https://github.com/jorgenschaefer/elpy/pull/1343))

I made a some tests, the four snippets concerned by the modifications ('_new', '_init', 'class' and 'super') seem to work fine.

I had to an additional quick fix (line 59) for the 'super' snippet to work.

### CODE REVIEW

**Comment by sten0** [comment]
Concerning af1347d:  Oh my, `yas-snips-rpc-python-command` was sloppy of me!  Thank you so much for catching it, frankly I'm embarrassed to have missed this issue.  Do you mind if I delay a day or two to do a bit of research/learning for a proposal I'd like to add a commit on top of af1347d, and do you mind if I commit to your fork?  For what I've read it's permitted by default on github, but it's always polite to ask first, you know :-)

**Comment by galaunay** [comment]
That's why some tests would be nice :).

Sure, commit where it is the more convenient for you.

**Comment by galaunay** [comment]
I assume that this can be closed.
Please re-open if it is not the case

**Comment by sten0** [comment]
Oh, yes, probably, because your commits are present (rebased/squashed as discussed) on https://github.com/AndreaCrotti/yasnippet-snippets/pull/278.  @AndreaCrotti is going to move forward with merging the non-conflicting no elisp dependency snippets, and later it looks like we'll have a round three of merging the problematic ones.  I'm starting to suspect it might be faster/easier to just rewrite them with equivalent functionality :-p

**Pull request closed without merging**
